### PR TITLE
very important change

### PR DESCRIPTION
**Pull request by riptl**
hello what is the licensing cost of this coc

### CODE REVIEW

**Comment by dm4uz3** [comment]
what and why did you PR for this

**Review by dm4uz3 — APPROVED** [review]
review

**Comment by riptl** [comment]
[5gum.zip](https://github.com/dm4uz3/good-CoC/files/2597878/5gum.zip)

**Comment by riptl** [comment]
image image image
image
image image image
image
image image image

**Comment by riptl** [comment]
image

**Pull request closed without merging**
